//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Ambulances = new HashSet<Ambulance>();
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string phone { get; set; }
        public string Status { get; set; }
        public string User_Type { get; set; }
        public string password { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Ambulance> Ambulances { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
